language: node_js

node_js:
  - "6"

branches:
  only:
    - web

install:
  - npm install -g codecov
  - npm install

script:
  - npm run-script test-cov
  - npm run-script build

after_success:
  - codecov
